version: "2"
services:
  php71:
    build:
      context: .
      args:
        PHP_VERSION: 7.1
    container_name: php71
    restart: always
    working_dir: /usr/websites
    volumes:
    - ${WEB_ROOT}:/usr/websites
    - ${PHP_CONFIG}/php.ini:/usr/local/etc/php/php.ini
    - ${PHP_CONFIG}/php-fpm.conf:/usr/local/etc/php-fpm.conf
    - ${PHP_CONFIG}/php-fpm.d:/usr/local/etc/php-fpm.d
    - ${LOG}/php/error.log:/usr/local/php/log/error.log
    environment:
      TZ: "${TZ}"
    ports:
    - 9000:9000
    networks:
      - static-network

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ${NGINX_CONFIG}/nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_CONFIG}/conf.d:/etc/nginx/conf.d
      - ${LOG}/nginx:/var/log/nginx/
      - ${WEB_ROOT}:/usr/websites
    networks:
      - static-network

    ports:
      - "80:80"
      - "433:433"
    environment:
      TZ: "${TZ}"

  db:
    #构建mysql镜像
    image: ${MYSQL_IMAGE}
    container_name: db-mysql
    environment:
      TZ: "${TZ}"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ${MYSQL_CONFIG}:/etc/mysql     # mysql 配置
      - ${MYSQL_LOG}:/var/log/mysql    # mysql 日志
      - ${MYSQL_DATA}:/var/lib/mysql   # mysql 数据
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
      --max_connections=1000
    networks:
      - static-network



networks:
  static-network:
    ipam:
      config:
        - subnet: 172.30.0.0/16

